nicenotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from rest_framework.routers import APIRootView
from rest_framework.authtoken.views import obtain_auth_token

from accounts.views import UserViewSet
from notes.views import NoteViewSet

note_list = NoteViewSet.as_view({
        'get': 'list',
        'post': 'create',
})

note_detail = NoteViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'patch': 'partial_update',
        'delete': 'destroy',
})

user_list = UserViewSet.as_view({
    'get': 'list',
    'post': 'create',
})

user_detail = UserViewSet.as_view({
    'get': 'retrieve',
})

urlpatterns = [
        path('api/token/', obtain_auth_token, name='api-token'),
        path('api/users/', user_list, name='user-list'),
        path('api/users/me/', user_detail, name='user-detail'),
        path('api/notes/', note_list, name='note-list'),
        path('api/notes/<int:pk>/', note_detail, name='note-detail'),
        path('', TemplateView.as_view(template_name='notes/index.html'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, mobile, password, **extra_fields):
        if not mobile:
            raise ValueError('The given mobile must be set')
        user = self.model(mobile=mobile, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, mobile, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(mobile, password, **extra_fields)

    def create_superuser(self, mobile, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(mobile, password, **extra_fields)

class CustomUser(AbstractBaseUser):
    full_name = models.CharField(max_length=40)
    mobile = models.CharField(max_length=10, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'mobile'
    EMAIL_FIELD = 'mobile'
    REQUIRED_FIELD = ['full_name']

    objects = CustomUserManager()
    
    def get_full_name():
        return self.full_name

    def get_short_name():
        return self.full_name


notes/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Note(models.Model):
    createdon = models.DateTimeField(auto_now_add=True)
    modifiedon = models.DateTimeField(auto_now=True)
    content = models.TextField(blank=True, default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
    edit_access_to = models.ManyToManyField(User, related_name='edit_access_to', blank=True)
    view_access_to = models.ManyToManyField(User, related_name='view_access_to', blank=True)

    def __str__():
        return "A note by {}, created on {} and last modified on {}".format(
                self.owner, self.createdon, self.modifiedon
                )

accounts/views.py
from django.contrib.auth import get_user_model

from rest_framework import status, mixins, viewsets, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token

from .serializers import UserSerializer

User = get_user_model()

class IsAuthenticatedOrCreateOnly(permissions.BasePermission):
    """
    The request is authenticated as a user, or is a POST request to create a new user.
    """
    def has_permission(self, request, view):
        return bool(
                request.method == 'POST' or
                request.user and 
                request.user.is_authenticated
        )

class UserViewSet(mixins.CreateModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    #search_fields = ('full_name', User.USERNAME_FIELD)
    
    permission_classes = [IsAuthenticatedOrCreateOnly]
    #filter_backends = ()

    def list(self, request, *args, **kwargs):
        queryset = User.objects.exclude(auth_token=request.auth)
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request, *args, **kwards):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        token = Token.objects.create(user=user)
        json = serializer.data
        json['token'] = token.key
        headers = self.get_success_headers(serializer.data)
        return Response(json, status=status.HTTP_201_CREATED, headers=headers)

    def retrieve(self, request, *args, **kwargs):
        queryset = User.objects.get(auth_token=request.auth)
        serializer = self.get_serializer(queryset, show_access_only=True)
        return Response(serializer.data)


notes/views.py
from rest_framework import status, permissions, viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Note
from .serializers import NoteSerializer

class NoteViewSet(viewsets.ModelViewSet):
    """
    List the user's notes or create a new note.
    """
    permission_classes = [permissions.IsAuthenticated]

    serializer_class = NoteSerializer
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    def get_queryset(self):
        user = self.request.user
        qs1 = user.notes.all()
        qs2 = user.edit_access_to.all()
        qs3 = user.view_access_to.all()

        has_pk = bool(self.kwargs.get('pk', None) is not None)
        if self.request.method == 'GET' and has_pk:  
            return qs1 | qs3
        elif self.request.method == 'PUT' or self.request.method == 'PATCH':
            return qs1 | qs2
        else:
            return qs1

notes/templates/notes/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Nice Notes</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'notes/vendor/pure.min.css' %}">
    <link rel="stylesheet" href="{% static 'notes/vendor/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'notes/css/styles.css' %}">
    <script type="text/html" id="login-template">
        <form class="pure-form pure-form-stacked" action="" method="post">
          <fieldset>
            <legend>Login</legend>
            <label for="id_username">Mobile</label>
            <input id="id_username" type="text" maxlength="10" name="username" required>
            <label for="id_login_password">Password</label>
            <input id="id_login_password" type="password" name="password" required>
            <input class="pure-button pure-button-primary" type="submit" value="Login">
          </fieldset>
        </form>
    </script>
    <script type="text/html" id="register-template">
        <form class="pure-form pure-form-stacked" action="" method="post">
          <fieldset>
            <legend>Register</legend>
            <label for="id_mobile">Mobile</label>
            <input id="id_mobile" type="text" maxlength="10" name="mobile" required>
            <label for="id_full_name">Full Name</label>
            <input id="id_full_name" type="text" maxlength="30" name="full_name" required>
            <label for="id_password">Password</label>
            <input id="id_password" type="password" name="password" required>
            <input class="pure-button pure-button-primary" type="submit" value="Register">
          </fieldset>
        </form>
    </script>
    <script type="text/html" id="header-template">
      <div class="pure-menu custom-menu">
        <h1 class="pure-menu-heading custom-menu-heading">Nice Notes</h1>
      <% if (authenticated) { %>
          <nav class="pure-menu-list custom-menu-list">
            <li class="pure-menu-item <% if (location.hash === '') { %>custom-menu-selected<% } %>">
              <a class="pure-menu-link custom-menu-link" href="#">Your Notes</a>
            </li>
            <li class="pure-menu-item <% if (location.hash === '#shared') { %>custom-menu-selected<% } %>">
              <a class="pure-menu-link custom-menu-link" href="#shared">Shared Notes</a>
            </li>
            <li class="pure-menu-item">
              <a class="pure-menu-link custom-menu-link" id="logout" href="#">Logout</a>
            </li>
          </nav>
      <% } %>
      </div>
    </script>
    <script type="text/html" id="notes-template">
      <h2><%- title %></h2>
      <% if (!sharedView) { %>
        <button class="pure-button pure-button-primary" id="new-note">Add Note</button>
      <% } %>
          <div class="pure-g notes">
        <% if (notes !== null && notes.length !== 0) { %>
          <% _.each(notes.models, function(note){ %>
            <div class="pure-u-1 note" data-id="<%- note.get('id') %>">
              <p class="content"><%- note.get('content') %></p>
              <p>
                <span>Created: <%- note.get('createdon') %></span>
                <span>Modified: <%- note.get('modifiedon') %></span>
              </p>
              <% if (!sharedView || note.get('access') === 'edit') { %>
              <button class="pure-button pure-button-primary edit-note">Edit</button>
              <% } %>
              <% if (!sharedView) { %><button class="pure-button pure-button-primary share-note">Share</button>
              <button class="pure-button delete-note">Delete</button>
              <% } %>
            </div>
          <% }); %>
        <% } else if (notes.length === 0) { %>
                <% if (sharedView) { %>
            <div class="pure-u-1 gray"><p>Nobody's shared anything with you. Sorry 'bout that.</p></div>
                <% } else { %>
            <div class="pure-u-1 gray"><p>You've got no notes. Why don't you make one?</p></div>
                <% } %>
        <% } %>
            </div>
    </script>
    <script type="text/html" id="create-note-template">
      <form class="pure-form pure-form-stacked" action="" method="post">
        <textarea id="id_content" name="content"></textarea>
        <input class="pure-button pure-button-primary" type="submit" value="Add Note">
        <input class="pure-button pure-button-primary" type="reset" value="Cancel">
        {% csrf_token %}
      </form>
    </script>
    <script type="text/html" id="edit-note-template">
      <form class="pure-form pure-form-stacked" action="" method="post">
        <textarea id="id_content" name="content"><%- note.get('content') %></textarea>
        <input class="pure-button pure-button-primary" type="submit" value="Edit Note">
        <input class="pure-button pure-button-primary" type="reset" value="Cancel">
        {% csrf_token %}
      </form>
    </script>
    <script type="text/html" id="share-note-template">
      <form class="pure-form" action="" method="post">
          <input id="search" placeholder="Search name or number" type="search">
          <input class="pure-button pure-button-primary" type="reset" value="Cancel">
        {% csrf_token %}
      </form>
    </script>
    <script type="text/html" id="user-list-template">
      <thead><tr><th>Mobile</th><th>Full Name</th><th>Access</th></tr></thead>
      <tbody>
      <% if (users !== null && users.length !== 0) { %>
          <% _.each(users, function (user) { %>
               <tr data-user-id="<%- user.get('id') %>">
                 <td class="mobile"><%- user.get('mobile') %></td>
                 <td class="full_name"><%- user.get('full_name') %></td>
                 <td>
              <select id="id_access" name="access">
                <option value="none" <% if (user.get('access') === 'none') { %>selected<% } %>>None</option>
                <option value="view" <% if (user.get('access') === 'view') { %>selected<% } %>>View</option>
                <option value="edit" <% if (user.get('access') === 'edit') { %>selected<% } %>>Edit</option>
              </select>
              </td>
               </li>
          <% }) %>
        <% } %>
        </tbody>
    </script>
  </head>
  <body>
    <section id="content"></section>
    <script src="{% static 'notes/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'notes/vendor/underscore.min.js' %}"></script>
    <script src="{% static 'notes/vendor/backbone.min.js' %}"></script>
    <script src="{% static 'notes/vendor/jquery-ui.min.js' %}"></script>
    <script id="config" type="text/json">
      {
        "models": {},
        "collections": {},
        "views": {},
        "router": null,
        "api": {
          "me": "/api/users/me",
          "users": "/api/users/",
          "notes": "/api/notes/"
        },
        "apiLogin": "{% url 'api-token' %}"
      }
    </script>
    <script src="{% static 'notes/js/app.js' %}"></script>
    <script src="{% static 'notes/js/models.js' %}"></script>
    <script src="{% static 'notes/js/views.js' %}"></script>
    <script src="{% static 'notes/js/router.js' %}"></script>
  </body>
</html>